version: 0.2

phases:
  install: 
    commands:
      - echo Installing dependancies...
      - npm install
  build:
    commands: 
      - echo building...
      - npm run build
artifacts:
  files: 
    - build/**/*
  discard-paths: yes